site_name: Siddhi-Store-HBase
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Store HBase: index.md
- API Docs:
  - 4.0.0-M12-SNAPSHOT: api/4.0.0-M12-SNAPSHOT.md
- License: license.md
theme: material
